name: Deploy to Kube

on:
  workflow_call:
    inputs:
      app-name:
        required: true
        type: string
      app-target:
        required: true
        type: string
      # REGISTRY:
      #   required: true
      # k8s-config:
      #   required: true
    secrets: 
      REGISTRY:
        required: true
      K8S_DEV: 
        required: true

jobs:
  deploy-k8s:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Deploy
      env:
        K8S_DEV: ${{secrets.K8S_DEV}}
        REGISTRY: ${{ secrets.REGISTRY }}
        APP: ${{ inputs.app-name }}
        APPTARGET: ${{inputs.app-target}}
      run: |
        curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
        chmod +x kubectl
        mv kubectl /usr/local/bin/
        cd ~
        mkdir .kube
        echo "$K8S_DEV" > .kube/config
        kubectl set image deployment/$APP $APPTARGET=$REGISTRY:$GITHUB_SHA
        kubectl rollout restart deployment/$app
