name: Package Vulnerability Scanning
on: [workflow_call]

jobs:
  osv-scanner:
    runs-on: ubuntu-latest
    name: OSV Scanner
    container: pandeptwidyaop/osv-scanner
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run OSV Scanner
        run: |
            test -f ./osv-config.toml &&  osv-scanner --config=./osv-config.toml -r . || osv-scanner -r
